### ISSUE TITLE
Speed up the FPS?

### ISSUE THREAD

**Issue by NeighborhoodCoding** [Chrispresso/SuperMarioBros-AI#1]
Hi. Your code is the best one ever..

I just wonder...can I speed up(Frame per second    up) when the visualization is on?

Thank you.

**Comment by Chrispresso** [comment]
Hi!

For speeding up with visualization, you can try setting a higher FPS (like 100 or even 1000) and hitting "Ctrl + V" to hide the visualization on that screen. PyQt can refresh at the rate of your monitor from what I've experienced. This causes you to only be able to have the network run 60 times/second. That is the main reason I allow you to run without visualization, in hopes that your training can be faster.
